### ISSUE TITLE
Suggest a feature - When linking, roles will be get to users in Discord.

### ISSUE THREAD

**Issue by mtmtyu** [MC-Linker/Discord-Linker#1]
Once linked, we suggest features that will grant roles to users within Discord.

**Comment by Lianecx** [comment]
You can already do that using the Linked Roles feature:
If you add a role, you can go to the links tab and add the "MC Linker" requirement there like this:
![image](https://github.com/user-attachments/assets/f3f08541-798a-4e74-a9dd-2912c3bfa84e)

Here's more info about Linked Roles: https://support.discord.com/hc/en-us/articles/10388356626711-Connections-Linked-Roles-Admins
We also made a video about this topic: https://www.youtube.com/watch?app=desktop&v=bcTYLWUV-k8&pp=ygUKI3ZsaW5rZXJtYw%3D%3D

Let me know if you need any more help or join the [support/community server](https://discord.gg/rX36kZUGNK) :)

**Comment by mtmtyu** [comment]
Thank you for teaching me!
