### ISSUE TITLE
Reply Username is the wrong username

### ISSUE THREAD

**Issue by Kazii78** [MC-Linker/Discord-Linker#2]
```
# %reply_username% is the username of the person who sent the message that was replied to
reply_message: "&l&7(replying to %reply_username%) &8->&r %reply_message_reduced% \n &l&9Discord &8| &l&7%username% &8>>&r %message%"
```
%reply_username% does not fetch the username of the person that was replied to, but the person that replied to the user.

This means:

(replying to reply_username) -> example message 1
 Discord | username >> example message 2
 
 becomes
 
 (replying to john) -> hello
 Discord | john >> hello kayden
 .
 
 Instead it should be:
 
 (replying to reply_username) -> example message 1
 Discord | username >> example message 2
 
 becomes
  (replying to kayden) -> hello
 Discord | john >> hello kayden
 .

**Comment by Lianecx** [comment]
I believe i've found the issue to this (it was a typo in the bot)
Can you tell me if everything works fine now?

**Comment by Kazii78** [comment]
I will update the plugin. I will post another comment after I have done.
My mistake, I didn't acknowledge you saying "bot", I'll test it.

**Comment by Kazii78** [comment]
Yup! The issue's been resolved. Thank you!
It shows the proper username now.
